project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - project-log.qmd
    - wikidata.qmd
    - wikidata-item.ipynb

authour: 
 name: "Zeinab Sepah Vand"
 orcid: "0009-0000-2628-4345"
 
website:
  title: "BIM Prototype 02"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project-log.qmd
        text: Project Log
      - href: wikidata.qmd
        text: Wikidata
      - href: wikidata-item.ipynb
        text: Item Profile

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
